### ISSUE TITLE
Bermuda Syndrome & Commander Genius missing line to launch executable

### ISSUE THREAD

**Issue by JazzJohannes** [jxded/anbernic-pm-launchscripts#2]
The scripts for Bermuda Syndrome (it has bs.exe and not just the one bs via gotobyk) & Commander Genius are missing the line to actually launch an executable

**Comment by jxded** [comment]
Hi, the scripts use a linux executable launcher (the binaries bs, CGeniusExe) for the ports to run. There's no need to reference the actual .exes, the referenced executables should be in the portmaster package for the games.

**Comment by JazzJohannes** [comment]
Hmm... they keep crashing on launch, so... did you actually try running those two yourself?

**Comment by jxded** [comment]
Just verified that CG runs fine.. I dont have the files for bermuda so I will have to check that later.
If you're crashing, there should be a log.txt file in the game directory that should give some insight.

**Comment by JazzJohannes** [comment]
This is the contents of the log.txt file:
`n: Initializing ThreadPool...
n: Installing CrashHandler .. registered simple resuming signal handler
n: ThreadPool creating 5 threads ...
n: Configuration filename is: cgenius.cfg
 unpacking...........end`

**Comment by JazzJohannes** [comment]
And "Bermuda Syndrome" to "Bermuda"
